apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: object-detection-v1742388115424
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-v1742388115424
  name: object-detection-v1742388115424
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
