apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: object-detection-v1742388115424-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-v1742388115424-database
  name: object-detection-v1742388115424-database
spec:
  ports:
    - port: 
      protocol: TCP
      targetPort: 
  selector:
    app.kubernetes.io/instance: object-detection-v1742388115424-database
