apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: object-detection-v1742388115424
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-v1742388115424
  name: object-detection-v1742388115424
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: object-detection-v1742388115424
